openapi: 3.0.0
info:
  title: Information API
  version: 1.0.0
  description: 'StreamHub Information API - reads Video, User and other information'
  contact:
    name: Elias Huber
    url: 'http://www.huber.host'
    email: elias@huber.host
  termsOfService: 'http://streamhub.huber.host/tos'
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
servers:
  - url: 'http://informationApi-api-v1-edev-streamhub.0.0.0.0.xip.io:8093'
    description: informationApi
paths:
  '/video/{hash}':
    get:
      summary: Video GET endpoint
      tags:
        - video
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  video:
                    $ref: '#/components/schemas/Video'
                required:
                  - video
                readOnly: true
              examples: {}
      operationId: getVideoByHash
      description: Get a video by hash
    parameters:
      - schema:
          type: string
          pattern: '^[A-Za-z0-9]+$'
          minLength: 8
          maxLength: 16
        name: hash
        in: path
        required: true
        description: Hash Field
components:
  schemas:
    Video:
      type: object
      title: Video
      description: Video Model
      x-examples: {}
      additionalProperties: false
      x-tags:
        - video
      properties:
        hash:
          $ref: '#/components/schemas/HashField'
        title:
          type: string
          maxLength: 70
        description:
          type: string
          maxLength: 5000
        uploadDate:
          type: string
          format: date-time
          readOnly: true
        location:
          $ref: '#/components/schemas/HashField'
        type:
          type: array
          uniqueItems: true
          items:
            type: string
            enum:
              - dash
              - hls
              - other
      required:
        - hash
        - title
        - description
        - uploadDate
        - location
        - type
    HashField:
      type: string
      title: HashField
      pattern: '^[A-Za-z0-9]+$'
      minLength: 8
      maxLength: 16
  securitySchemes: {}
  responses: {}
  parameters: {}
  examples: {}
tags:
  - name: location
  - name: video
