openapi: 3.0.0
info:
  title: Information Database Driver
  version: 1.0.0
  description: |-
    Driver to uniformly get data from the database.
    Executes basic CRUD operations.
    I don't want all of my apis and serivces to directly access my databases, thus this driver.
    Luckly noone, except interns will ever see this xD

    Yea as i said: INTERNAL ONLY
  contact:
    name: Elias Huber
    url: 'http://www.huber.host'
    email: elias@huber.host
  termsOfService: 'http://streamhub.huber.host/tos'
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
servers:
  - url: 'http://informationDatabaseDriver-api-v1-edev-streamhub.0.0.0.0.xip.io:8095'
    description: informationDatabaseDriver
paths:
  /VideoInformation:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideoInformation'
      operationId: getVideoInformation
      description: get video information
      parameters:
        - schema:
            type: array
          in: query
          name: selector
          description: selector for data
          style: form
          explode: true
          required: true
  /VideoIdFromHash:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideoIdFromHash'
      operationId: getVideoIdFromHash
      description: get video id from hash
      parameters:
        - schema:
            type: array
          in: query
          name: selector
          description: selector for data
          required: true
          style: form
          explode: true
components:
  schemas:
    VideoIdFromHash:
      type: object
      title: VideoIdToHash
      description: Identifier to Hash
      additionalProperties: false
      properties:
        hash:
          $ref: ./Hash.v1.yaml
        id:
          $ref: ./Identifier.v1.yaml
      required:
        - hash
        - id
    VideoInformation:
      type: object
      title: Video
      description: Video Model
      additionalProperties: false
      properties:
        hash:
          $ref: ./Hash.v1.yaml
        title:
          type: string
          maxLength: 70
        description:
          type: string
          maxLength: 5000
        uploadDate:
          type: string
          format: date-time
          readOnly: true
      required:
        - hash
        - title
        - description
        - uploadDate
        - type
  parameters:
    Hash:
      name: hash
      in: query
      required: true
      schema:
        type: string
        pattern: '^[A-Za-z0-9]+$'
        minLength: 8
        maxLength: 16
      description: A 8 to 16 characters long hash
  securitySchemes: {}
tags:
  - name: video
