openapi: 3.0.0
info:
  title: Media Stream Relay
  version: 1.0.0
  description: StreamHub Media Stream Relay - returns a Media Stream by header information
  contact:
    name: Elias Huber
    url: 'http://www.huber.host'
    email: elias@huber.host
  termsOfService: 'http://streamhub.huber.host/tos'
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
servers:
  - url: 'http://information-api-v1-edev-streamhub.0.0.0.0.xip.io:8094'
    description: mediaStreamRelay
paths:
  '/{file}':
    parameters:
      - in: path
        name: file
        required: true
        schema:
          type: string
          maxLength: 60
        description: File name
    get:
      summary: Your GET endpoint
      tags:
        - stream
      responses:
        '200':
          description: OK
          content:
            application/vnd.apple.mpegurl:
              schema: {}
            application/dash+xml:
              schema: {}
            video/mp4:
              schema: {}
            application/x-mpegURL:
              schema: {}
            video/MP2T:
              schema: {}
          headers: {}
      operationId: getStream
      description: Get the requested media
      parameters:
        - $ref: '#/components/parameters/Hash'
components:
  schemas: {}
  parameters:
    Hash:
      name: Hash
      in: header
      required: true
      schema:
        type: string
        pattern: '^[A-Za-z0-9]+$'
        minLength: 8
        maxLength: 16
      description: Generic hash
tags:
  - name: stream
